on:
  pull_request:
    branches: main
  schedule:
    - cron: "0 4 * * *"

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: '3.6'}
          - {os: ubuntu-18.04,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-18.04,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2

      - name: Test coverage
        if: ${{ runner.os == 'Linux' && matrix.config.r == 'release'}}
        run: |
          install.packages('covr')
          covr::codecov()
        shell: Rscript {0}

      - name: Render rmd
        if: ${{ github.event_name == 'pull_request' && runner.os == 'Linux' }}
        run: |
          devtools::install()
          rmarkdown::render('README.Rmd')
        shell: Rscript {0}

      - name: Commit changes
        if: ${{ github.event_name == 'pull_request' && runner.os == 'Linux' }}
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Update README.md'
          add: 'README.md'
